### ISSUE TITLE
Question about fft

### ISSUE THREAD

**Issue by xuxuxu0701** [HarrisonKramer/optiland#14]
with the code below
```python
import numpy as np
from optiland import optic, psf, materials

class CookeTriplet(optic.Optic):
    def __init__(self):
        super().__init__()
        germanium = materials.IdealMaterial(n=4.00437257098)
        self.add_surface(index=0, radius=np.inf, thickness=np.inf)
        self.add_surface(index=1, radius=1.091514758603290E+002, thickness=2.000000000000000E+000, material=germanium)
        self.add_surface(index=2, radius=4.070191892848400E+003, thickness=1.061772791539110E+001)
        self.add_surface(index=3, radius=-1.063834720570420E+001, thickness=4.000000000000000E+000, material=germanium, is_stop=True)
        self.add_surface(index=4, radius=-1.387594282307140E+001, thickness=1.533534747011550E+001)
        self.add_surface(index=5, radius=21, thickness=4.000000000000000E+000, material=germanium)
        self.add_surface(index=6, radius=3.187863257337930E+001, thickness=7.999901308063720E+000)
        self.add_surface(index=7, rx=np.radians(0.))


        self.set_aperture(aperture_type='EPD', value=9.)

        self.set_field_type(field_type='angle')
        self.add_field(y=0)
        self.add_field(y=5)
        self.add_field(y=9)

        self.add_wavelength(value=12, is_primary=True)

lens = CookeTriplet()

lens_psf = psf.FFTPSF(lens, field=(0, 1), wavelength=12)
lens_psf.view(num_points=512)
```
got the result like this 
![image](https://github.com/user-attachments/assets/28f14f85-d264-4674-aef7-297acc7beaed)
but compared with the result in zemax it seems different
![image](https://github.com/user-attachments/assets/81194411-209d-43e4-ac39-26a3a4cc95c1)
![image](https://github.com/user-attachments/assets/8eed34af-4b36-4b31-82b4-152b07d647a1)
![image](https://github.com/user-attachments/assets/f80237fa-0062-4016-b711-03e3029c7ba7)
![image](https://github.com/user-attachments/assets/f0f4629b-f409-4f94-bc49-453c047e94f5)

_Edited by Kramer Harrison on Dec 1, 2024 to format code as Python._

**Comment by HarrisonKramer** [comment]
Hi xuxuxu0701,

Thanks for opening this issue and providing all relevant information and screenshots.

I think the difference is due only to visualization defaults. If I change the PSF code to
```python
lens_psf = psf.FFTPSF(lens, field=(0, 1), wavelength=12, num_rays=256)
lens_psf.view(num_points=256, threshold=0.005)
```
then the resulting map appears qualitatively similarly to the Zemax result. I overrode some of the Optiland plotting settings (such as the colormap) to match Zemax and I get this result:

![image](https://github.com/user-attachments/assets/ed0ad127-14bb-420a-a372-2a52235d6f13)

I don't expect the images to match exactly on the pixel level due to e.g. numerical effects, differences in the calculation steps, and/or interpolation.

In general, if you find the PSF doesn't quite match your expectation (or another program), consider changing:

- `num_rays` argument to `psf.FFTPSF` to change pupil sampling.
- `num_points` argument to `view` to change interpolation resolution.
- `threshold` to control extent of plotting image.

Hope this helps! Let me know if you have any other questions.

Regards,
Kramer

**Comment by xuxuxu0701** [comment]
Thanks for your reply！and you said you change the PSF code to
```
lens_psf = psf.FFTPSF(lens, field=(0, 1), wavelength=12, num_rays=256)
lens_psf.view(num_points=256, threshold=0.005)
```
It seems the same as athe code I approved. Just num_ray=256 is different(default is 128), and threshold=0.005 is the default num.
So you said you overrode some of the Optiland plotting settings (such as the colormap). Did you mean you change the code IN<psf.py> of optiland in line 122
`cbar = plt.colorbar(im)`
to get result looks like in Zemax.
I wonder the code change, and how I can get the same result like yours!
THANKS AGAIN FOR YOUR HELP！

**Comment by xuxuxu0701** [comment]
Besides, in zemax the max value is not in the region near the center

![image](https://github.com/user-attachments/assets/b638bdc1-dfb6-4b0c-bffe-792b69856ac4)

And with Optiland, the max value is not in the same region ?

![image](https://github.com/user-attachments/assets/9b434c65-12c3-47d8-8125-da921fe0b92c)

**Comment by HarrisonKramer** [comment]
### FFT PSF Defaults
The default `threshold` setting in Optiland is 0.05, which results in an image extent of approximately ±225 µm. I used a value of 0.005, which, while a small difference, leads to a larger image extent. This behavior is expected as lower threshold values include fainter contributions to the PSF in the visualization.

### Changes to make the Optiland plot more "Zemax-like"
In psf.py, I updated the function FFTPSF._plot_2d to the following:
```python
im = ax.imshow(image/100, norm=norm, extent=extent, cmap='jet')
```

Here, I divided the data by 100 to convert from percent to decimal. I also used the jet colormap to match the appearance of Zemax plots. However, I will point out that colormaps like jet and rainbow, while visually striking, are not ideal for scientific visualization (IMO). They can introduce perceptual biases and make it harder to interpret subtle features in the data. This is one reason I've avoided using them in Optiland. That said, the choice of colormap is entirely up to you, of course. 

Additionally, I updated the colorbar label to reflect the change in units:

```python
cbar.ax.set_ylabel('Relative Intensity', rotation=270)
```

### On differences in location of the PSF peak

Without access to the inner workings of Zemax, debugging discrepancies in PSF peak location can be challenging. Optiland's algorithm adheres to the standard approach for FFT-based PSF calculations and is expected to be robust. However, minor differences may arise due to sampling or interpolation effects. This is especially noticeable when the optical system is far from the diffraction limit, as is the case in this example.

For higher accuracy, I recommend using the Huygens PSF method, which accounts for these effects more rigorously. Implementation of the Huygens PSF is on the Optiland roadmap, and I hope to dedicate time to it in the coming months.

Thanks again for your interest and for opening this issue!

Regards,
Kramer

**Comment by HarrisonKramer** [comment]
It's been a month since the last follow-up here, so I'll close the issue. Feel free to open another if you have any other questions or remarks.

Regards,
Kramer
