### ISSUE TITLE
Adding a Ronchi Ruler and a Beamsplitter

### ISSUE THREAD

**Issue by hemkumarsrinivas** [HarrisonKramer/optiland#31]
Hi,
Over the last couple of weeks, I got to try many of the examples provided and was trying to implement the Ronchi test for a simple lens system. I modified the example for custom coatings to generate a Ronchi pattern on the surface, using scipy's squarewave function :

```python
    class Ronchi(BaseCoating):
        def reflect(self, rays, nx, ny, nz):
            # for reflection, we leave the rays unchanged
            return rays

        def transmit(self, rays, nx, ny, nz):
              rays.i = signal.square(6*np.pi*rays.x) + 1
              return rays
```

To test it, I just sent a bunch of parallel rays and looked at the 2D Ray distribution on the image plane.
![image](https://github.com/user-attachments/assets/f84108c4-5c94-476e-8262-5e27a0bad528)

The question here is:  Would this be the right approach ultimately? It seems to work along with a lens system, where I try to project the pattern. It would be great if you could share your thoughts on this.

Going further, I also tried to modify the same example to create a beamsplitter. While defining the surfaces, first only the coating parameter was added and later the material was also changed to mirror. In both cases, I did not get any result. Here's the code : 

```python
class BeamSplitter(BaseCoating):
    def reflect(self, rays, nx, ny, nz):
        # for reflection, we leave the rays unchanged
        rays.i=rays.x*0.5 # assuming a 50/50 beamsplitter
        return rays

    def transmit(self, rays, nx, ny, nz):
        rays.i = rays.x*0.5
        return rays

```

Any inputs/ideas, how this could be implemented ?

Regards,
Hem

_Edited by Kramer on Dec. 31 - change code format to Python_

**Comment by HarrisonKramer** [comment]
Hi Hem,

Thanks for your question and for exploring these advanced use cases.

## Ronchi Test

Your approach to simulating a Ronchi grating by applying a grid-like pattern on a surface using the `scipy.signal.square` function seems valid for a ray-based simulation. If your application relies purely on ray optics, this method should work fine. However, if diffraction effects are of interest (e.g., due to very fine gratings), Optiland’s raytracing framework won’t capture them, as it doesn’t model wave interference. This feature has been considered but is not currently planned.

## Beamsplitter

Regarding the beamsplitter, Optiland’s sequential raytracing framework doesn’t support splitting rays into multiple paths. A workaround is to trace rays twice - once for the reflected path and once for the transmitted path - and combine the results later. If you need to model interference, polarization (electric field vectors) must be included for each ray. These fields can then be coherently summed on the detection plane, and the squared magnitude gives the intensity pattern.

In general, it's best to be careful setting up components that are off the primary optical axis (i.e., z-axis). If you want fine control over the positions of every surface, you may want to manually define the coordinate systems of each.

### References
- [Example 1](https://github.com/HarrisonKramer/optiland/blob/master/docs/examples/Tutorial_10a_Custom_Surface_Types.ipynb) Shows how to manually define a coordinate system and surface. You could use a plane instead of a custom surface.
- [Example 2](https://github.com/HarrisonKramer/optiland/blob/master/docs/examples/Tutorial_6b_Introduction_to_Polarization.ipynb) Discusses polarization ray tracing.

Let me know if you’d like more clarification or guidance!

Regards,
Kramer

**Comment by hemkumarsrinivas** [comment]
Hi,
Thank you for the quick response. For the Ronchi test, right now I think Ray Optics alone will suffice for my application. For the beamsplitter, I think that the two examples you have provided will be a good starting point already. I will try writing a class for this in the coming days and get back to you if there are any additional questions or clairifications.
