### ISSUE TITLE
FFT PSF question and request for Huygens psf

### ISSUE THREAD

**Issue by xuxuxu0701** [HarrisonKramer/optiland#7]
Sorry i closed the issues not over

I use the code below and got error:

```
import numpy as np
from optiland import optic, psf

class CookeTriplet(optic.Optic):
    def __init__(self):
        super().__init__()

        self.add_surface(index=0, radius=np.inf, thickness=np.inf)
        self.add_surface(index=1, radius=22.01359, thickness=3.25896, material='SK16')
        self.add_surface(index=2, radius=-435.76044, thickness=6.00755)
        self.add_surface(index=3, radius=-22.21328, thickness=0.99997, material=('F2', 'schott'))
        self.add_surface(index=4, radius=20.29192, thickness=4.75041, is_stop=True)
        self.add_surface(index=5, radius=79.68360, thickness=2.95208, material='SK16')
        self.add_surface(index=6, radius=-18.39533, thickness=42.20778)
        self.add_surface(index=7, rx=np.radians(45.0))

        self.set_aperture(aperture_type='EPD', value=10)

        self.set_field_type(field_type='angle')
        self.add_field(y=0)
        self.add_field(y=14)
        self.add_field(y=20)

        self.add_wavelength(value=0.48)
        self.add_wavelength(value=0.55, is_primary=True)
        self.add_wavelength(value=0.65)

lens = CookeTriplet()

lens_psf = psf.FFTPSF(lens, field=(0, 0.1), wavelength=0.55)
lens_psf.view(num_points=128)
```
and got error:
Traceback (most recent call last):
File "C:\Users\Administrator\Downloads\optiland-master\temp.py", line 31, in
lens_psf.view(num_points=128)
File "C:\Users\Administrator\Downloads\optiland-master\optiland\psf.py", line 73, in view
min_x, min_y, max_x, max_y = self._find_bounds(threshold)
File "C:\Users\Administrator\Downloads\optiland-master\optiland\psf.py", line 284, in _find_bounds
min_x, min_y = np.min(non_zero_indices, axis=0)
File "<array_function internals>", line 200, in amin
File "D:\software\Anaconda\envs\py39\lib\site-packages\numpy\core\fromnumeric.py", line 2946, in amin
return _wrapreduction(a, np.minimum, 'min', axis, None, out,
File "D:\software\Anaconda\envs\py39\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

And when i only change the code like

`lens_psf = psf.FFTPSF(lens, field=(0, 1), wavelength=0.55)`

the program running normally, just very slow, and got like this
<img width="525" alt="psfcodelargefov" src="https://github.com/user-attachments/assets/8381f4de-8c53-458c-9905-7c15f11796d8">

For the Q2, I used code below

```
  import numpy as np
  from optiland import optic, psf
  
  
  class CookeTriplet(optic.Optic):
      def __init__(self):
          super().__init__()
  
          self.add_surface(index=0, radius=np.inf, thickness=np.inf)
          self.add_surface(index=1, radius=22.01359, thickness=3.25896,
                           material='SK16')
          self.add_surface(index=2, radius=-435.76044, thickness=6.00755)
          self.add_surface(index=3, radius=-22.21328, thickness=0.99997,
                           material=('F2', 'schott'))
          self.add_surface(index=4, radius=20.29192, thickness=4.75041,
                           is_stop=True)
          self.add_surface(index=5, radius=79.68360, thickness=2.95208,
                           material='SK16')
          self.add_surface(index=6, radius=-18.39533, thickness=42.20778)
          self.add_surface(index=7, rx=np.radians(45.0))
  
          self.set_aperture(aperture_type='EPD', value=10)
  
          self.set_field_type(field_type='angle')
          self.add_field(y=0)
          self.add_field(y=3)
          self.add_field(y=6)
  
          self.add_wavelength(value=0.48)
          self.add_wavelength(value=0.55, is_primary=True)
          self.add_wavelength(value=0.65)
  
          self.update_paraxial()
  lens = CookeTriplet()
  lens_psf = psf.FFTPSF(lens, field=(0, 0.5), wavelength=0.55)
  lens_psf.view(projection='2d', num_points=1024)
```
and got a result like this
<img width="525" alt="psfcode" src="https://github.com/user-attachments/assets/2a7dead9-ebc9-49ce-b6cb-60699f6d74a9">

compared with the result of fft psf in zemax, it seems different
<img width="923" alt="zemaxfftpsf" src="https://github.com/user-attachments/assets/6a15fae8-024a-4df2-8946-e623f00fea64">

and the lens data is here

<img width="918" alt="zemaxlesdata" src="https://github.com/user-attachments/assets/e2b0de0f-79a9-4817-b1e9-1c71fbf25f8f">

Optiland is the best open-source ray tracing, optical design, and analysis software I have used. It is extremely simple and efficient. I would greatly appreciate it if the Huygens PSF functionality could be added !

**Comment by HarrisonKramer** [comment]
Thanks for providing such a thorough description of the issue, including the code examples and Zemax screenshots.

I have confirmed that I can reproduce this error. I will investigate this further and come back here when I have an update. I will also investigate why the computation time dramatically increases under certain conditions.

I will add the Huygens PSF functionality as a feature in the roadmap and begin looking into how I can best implement this. Thanks for the suggestion!

**Comment by xuxuxu0701** [comment]
I find something in the file of Zemax about FFT PSF maybe helpful
<img width="513" alt="zemaxfile" src="https://github.com/user-attachments/assets/83166da0-e1e2-4ede-83c0-3fc7ba13053a">
Thus for the situation that the image plane was tilted with 45 degree, even the FFT PSF function in Zemax can't get the right PSF.
Using Huygens PSF at that time maybe more correct.
But I think in Zemax, they do more thing than just got the pupil function on the exit pupil and do FFT transform.
And under that situation, even the FFT PSF in Optiland got the same result it still meaningless. The Huygens PSF function is needed.
Whatever, Huygens PSF always get the right result.

**Comment by HarrisonKramer** [comment]
Thanks for adding additional information.

Indeed, while the FFT PSF has many limitations, it is much more computationally efficient than a direct integration approach (Huygens). I recognize the FFT PSF will not be representative in the case that the image plane is tilted by 45 degrees. However, it's often these corner cases where bugs or inefficiencies in the code can be found, which is why I am very glad you brought up this issue. My concern is less about its accuracy in this particular case, but more about the general robustness.

Therefore, my current plan is to:
1. Identify the root cause of the error you identified, correct the bug (if it exists), or have the code generate a more meaningful error message. I will do the same for the issue regarding the significant computation time increase.
2. Consider adding a warning when the FFT PSF is unlikely to be valid (e.g. the chief ray is at a large angle with respect to the image plane surface normal). I propose not to raise an error here, but prefer to leave it up to the user to decide when the FFT method is appropriate.
3. Bump up the priority of the "Huygens PSF" feature.

**Comment by HarrisonKramer** [comment]
I have finally had a chance to dig deeper into this issue and resolved the error and long simulation times.

First, the root cause of the error was related to how limits were determined for plotting the PSF. This had nothing to do with the actual PSF calculation itself. I now catch this issue in the code to prevent it from occurring.

Second, the long processing time was related to an intermediate interpolation I was performing for plotting purposes only. I updated the code to use a more efficient interpolation algorithm (scipy.ndimage.zoom), which speeds up the code substantially.

I also checked why there was a discrepancy between the computed PSF and Zemax result. which you point out above. This was simply due to differences in the sampling and display resolutions. If I use this code:

```python
lens = CookeTriplet()
lens_psf = psf.FFTPSF(lens, field=(0, 0.5), wavelength=0.55, num_rays=1024)
lens_psf.view(projection='2d', num_points=2048, threshold=0.001)
```

then I get the following image:
![image](https://github.com/user-attachments/assets/3533bc40-b691-477c-b0b1-d2056a201195)

The `num_rays` argument corresponds to the sampling resolution in Zemax, while `num_points` corresponds to the display resolution.

This is qualitatively similar to the image you provided, which I copy here:
![image](https://github.com/user-attachments/assets/e030c62f-5022-48a4-af1c-d2ae5ea2fc37)

After some final checks and testing, I will merge these issues into master and close the branch. I will proceed with development of the Huygens PSF feature in another branch. Thanks again for reporting this issue!
